create table "Interest"
(
    id      serial
        constraint interest_pk
            primary key,
    hashtag char(255) not null
);

alter table "Interest"
    owner to sammy;

grant select, usage on sequence "Interest_id_seq" to sammy;

create unique index interest_id_uindex
    on "Interest" (id);

grant delete, insert, references, select, trigger, truncate, update on "Interest" to sammy;

INSERT INTO public."Interest" (id, hashtag) VALUES (1, '3D printing                                                                                                                                                                                                                                                    ');
INSERT INTO public."Interest" (id, hashtag) VALUES (2, 'Aikido                                                                                                                                                                                                                                                         ');
INSERT INTO public."Interest" (id, hashtag) VALUES (3, 'Animals/pets/dogs                                                                                                                                                                                                                                              ');
INSERT INTO public."Interest" (id, hashtag) VALUES (4, 'Arts                                                                                                                                                                                                                                                           ');
INSERT INTO public."Interest" (id, hashtag) VALUES (5, 'Astronomy                                                                                                                                                                                                                                                      ');
INSERT INTO public."Interest" (id, hashtag) VALUES (6, 'Backpacking                                                                                                                                                                                                                                                    ');
INSERT INTO public."Interest" (id, hashtag) VALUES (7, 'Basketball                                                                                                                                                                                                                                                     ');
INSERT INTO public."Interest" (id, hashtag) VALUES (8, 'Beach/Sun tanning                                                                                                                                                                                                                                              ');
INSERT INTO public."Interest" (id, hashtag) VALUES (9, 'Beer Pong                                                                                                                                                                                                                                                      ');
INSERT INTO public."Interest" (id, hashtag) VALUES (10, 'Board games                                                                                                                                                                                                                                                    ');
INSERT INTO public."Interest" (id, hashtag) VALUES (11, 'Boxing                                                                                                                                                                                                                                                         ');
INSERT INTO public."Interest" (id, hashtag) VALUES (12, 'Camping                                                                                                                                                                                                                                                        ');
INSERT INTO public."Interest" (id, hashtag) VALUES (13, 'Car Racing                                                                                                                                                                                                                                                     ');
INSERT INTO public."Interest" (id, hashtag) VALUES (14, 'Chess                                                                                                                                                                                                                                                          ');
INSERT INTO public."Interest" (id, hashtag) VALUES (15, 'Computer programming                                                                                                                                                                                                                                           ');
INSERT INTO public."Interest" (id, hashtag) VALUES (16, 'Cooking                                                                                                                                                                                                                                                        ');
INSERT INTO public."Interest" (id, hashtag) VALUES (17, 'Dancing                                                                                                                                                                                                                                                        ');
INSERT INTO public."Interest" (id, hashtag) VALUES (18, 'Fashion                                                                                                                                                                                                                                                        ');
INSERT INTO public."Interest" (id, hashtag) VALUES (19, 'Football                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (20, 'Games                                                                                                                                                                                                                                                          ');
INSERT INTO public."Interest" (id, hashtag) VALUES (21, 'Guitar                                                                                                                                                                                                                                                         ');
INSERT INTO public."Interest" (id, hashtag) VALUES (22, 'Handball                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (23, 'Hiking                                                                                                                                                                                                                                                         ');
INSERT INTO public."Interest" (id, hashtag) VALUES (24, 'Jogging                                                                                                                                                                                                                                                        ');
INSERT INTO public."Interest" (id, hashtag) VALUES (25, 'Judo                                                                                                                                                                                                                                                           ');
INSERT INTO public."Interest" (id, hashtag) VALUES (26, 'Lego                                                                                                                                                                                                                                                           ');
INSERT INTO public."Interest" (id, hashtag) VALUES (27, 'Magic                                                                                                                                                                                                                                                          ');
INSERT INTO public."Interest" (id, hashtag) VALUES (28, 'Marathon                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (29, 'Movies                                                                                                                                                                                                                                                         ');
INSERT INTO public."Interest" (id, hashtag) VALUES (30, 'Music                                                                                                                                                                                                                                                          ');
INSERT INTO public."Interest" (id, hashtag) VALUES (31, 'Nail Art                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (32, 'Origami                                                                                                                                                                                                                                                        ');
INSERT INTO public."Interest" (id, hashtag) VALUES (33, 'Painting                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (34, 'Poker                                                                                                                                                                                                                                                          ');
INSERT INTO public."Interest" (id, hashtag) VALUES (35, 'Pétanque                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (36, 'Quidditch                                                                                                                                                                                                                                                      ');
INSERT INTO public."Interest" (id, hashtag) VALUES (37, 'Robotics                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (38, 'Scuba Diving                                                                                                                                                                                                                                                   ');
INSERT INTO public."Interest" (id, hashtag) VALUES (39, 'Sudoku                                                                                                                                                                                                                                                         ');
INSERT INTO public."Interest" (id, hashtag) VALUES (40, 'Swimming                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (41, 'Tennis                                                                                                                                                                                                                                                         ');
INSERT INTO public."Interest" (id, hashtag) VALUES (42, 'Traveling                                                                                                                                                                                                                                                      ');
INSERT INTO public."Interest" (id, hashtag) VALUES (43, 'Urban Exploration                                                                                                                                                                                                                                              ');
INSERT INTO public."Interest" (id, hashtag) VALUES (44, 'Video Games                                                                                                                                                                                                                                                    ');
INSERT INTO public."Interest" (id, hashtag) VALUES (45, 'Volunteer                                                                                                                                                                                                                                                      ');
INSERT INTO public."Interest" (id, hashtag) VALUES (46, 'Warhammer                                                                                                                                                                                                                                                      ');
INSERT INTO public."Interest" (id, hashtag) VALUES (47, 'Writing                                                                                                                                                                                                                                                        ');
INSERT INTO public."Interest" (id, hashtag) VALUES (48, 'Yak polo                                                                                                                                                                                                                                                       ');
INSERT INTO public."Interest" (id, hashtag) VALUES (49, 'Yoga                                                                                                                                                                                                                                                           ');
INSERT INTO public."Interest" (id, hashtag) VALUES (50, 'Zumba                                                                                                                                                                                                                                                          ');